name: Build and Pack

#on:
#  push:
#    tags:
#      - 'v*'

on: 
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  pack:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
        rust: [stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
        components: rustfmt

    - name: fmt
      run: cargo fmt --all -- --check
      if: matrix.rust == 'stable'
    
    - name: build
      run: cargo build --release

    - name: pack
      uses: actions/upload-artifact@v2
      with:
        name: 'displayrecorder_${{ matrix.platform }}_${{ matrix.configuration }}'
        path: '.\target\release\displayrecorder*'
